- name: Configure backwnd server
  hosts: backend
  become: true
  vars:
    login_password: ExpenseApp@1
    login_host: mysql.lokiaws.online
  tasks:
  - name: Disable node js module
    ansible.builtin.command: "dnf module disable nodejs -y"
  
  - name: Enable node js
    ansible.builtin.command: "dnf module enable nodejs:20 -y"

  - name: Install node js
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - nodejs
    - mysql

  - name: Create user
    ansible.builtin.user:
      name: expense

  - name: Create app directory
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: download the backend code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip

  - name: unzip the code
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app
      remote_src: yes

  - name: install npm dependencies
    ansible.builtin.command: "npm install"
    args:
      chdir: /app

  - name: Copy backend service file
    ansible.builtin.copy:
      src: backend.service
      dest: /etc/systemd/system/backend.service

  - name: install pymysql 
    ansible.builtin.pip:
      name:
      - pymysql
      executable: pip3.9

  - name: import mysql data
    community.mysql.mysql_db:
      login_user: root
      login_password: "{{ login_password }}"
      login_host: "{{ login_host }}"
      name: all
      state: import
      target: /app/schema/backend.sql

  - name: Deamon reload
    ansible.builtin.systemd_service:
      state: restarted
      deamon_reload: yes
      name: backend
      

  