- name: Configure backwnd server
  hosts: backend
  become: true
  tasks:
  - name: Disable node js module
    ansible.builtin.command: "dnf module disable nodejs -y"
  
  - name: Enable node js
    ansible.builtin.command: "dnf module enable nodejs:20 -y"

  - name: Install node js
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: Create user
    ansible.builtin.user:
      name: expense