- name: mysql configuration
  hosts: mysql
  become: true
  vars:
    login_password: ExpenseApp@1
    login_host: mysql.lokiaws.online
  tasks:
  - name: install pymysql
    ansible.builtin.pip:
      name: pymysql
      executable: pip3.9

  - name: install mysql server
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: start mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: connect to the server
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ login_password }}"
      login_host: "{{ login_host }}"
    ignore_errors: yes
    register: mysql_info

  - name: setup mysql root login_password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ login_password }}"
    when: mysql_info.failed is true